name: Setup AWS for SST
description: Configure AWS credentials and prepare environment for SST deployment

inputs:
  role-to-assume:
    description: AWS IAM Role ARN to assume
    required: true
  aws-region:
    description: AWS region
    required: false
    default: ap-northeast-1

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    # GitHub Actions ランナーにプリインストールされた Pulumi が
    # SST 内部の Pulumi と競合するため削除
    - name: Remove pre-installed Pulumi
      shell: bash
      run: rm -rf /usr/local/bin/pulumi*
