name: Setup Bun
description: Setup Bun and install dependencies

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.5

    - name: Install dependencies
      shell: bash
      run: bun install
